### DISCUSSION TITLE
How to automate with switch events?

### DISCUSSION THREAD

**Discussion by nrenner73** [kingsleyadam/local-abbfreeathome-hass#104] [Q&A] [answered]
Probably not an issue but more a problem with understanding switch events.

I have a f@h switch in my bathroom, that is not connected to a f@h actuator. In HA I want to have an automation that switches on a Shelly plug s to start warm water circulation. I just want to switch it on, regardless of where I press the button. Switching it off is done by a timer.

I get the switch event in HA whenever I press top or bottom of the switch, regardless of the state. 
I tried implementing my automation, but with the example from the description, I can only trigger my automation whenever I have a state change.
This means when the state is off and I press on, the automation is triggered. Also when the state is on and I press off it is triggered as well.

But when the state is off and I press off, nothing happens. The same is with on state and pressing on.

Is there a way to just react to the event regardless of the state? Could you maybe point me in the right direction?

Thanks a lot!

**Comment by kingsleyadam** [comment]
A heads up, I converted this to a discussion.

**Comment by derjoerg** [comment]
Have you tried it without the `To``

```
trigger: state
entity_id:
  - event.sensoreinheit_1_fach_licht_dimm_ereignis_ch0000
```

**Comment by kingsleyadam** [comment, marked as answer]
Even though the [documentation](https://www.home-assistant.io/docs/automation/trigger/#state-trigger) says to set to or from to `null` to record all events.

> To trigger on all state changes, but not on changed attributes, set at least one of `from`, `to`, `not_from`, or `not_to` to null.

That actually doesn't seem to work for me.

This did work for me.

```yaml
alias: Rocker Pressed On
description: Do something when the rocker is pressed on.
triggers:
  - trigger: event
    event_type: state_changed
    event_data:
      entity_id: event.office_rocker_switch_event_ch0000
conditions: []
actions:
  - condition: template
    value_template: "{{ trigger.event.data.new_state.attributes.event_type == \"on\" }}"
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.3rd_floor_landing_light
mode: single
```
