### DISCUSSION TITLE
No import of scenes?

### DISCUSSION THREAD

**Discussion by mattberlinHA** [kingsleyadam/local-abbfreeathome-hass#145] [General]
Hello everybody,

I just tried this wonderful integration an found out that the scenes defined in F@H do not show up in HA? This it intended to be like that or is there something I did not setup properly?

BR

**Comment by derjoerg** [comment]
Hi @mattberlinHA 
Scenes are, regarding ABB, officially not supported through the local API.

Please look at https://developer.eu.mybuildings.abb.com/fah_local/concepts and search for 'Scenes', there are also workarounds explained.

**Comment by mattberlinHA** [comment]
Thanks. That is pretty advanced stuff. I already fail to create the virtual device :-(

<img width="895" alt="image" src="https://github.com/user-attachments/assets/7fd66423-f7a1-40e1-b532-3f5dcdc47214" />

Hopefully, there will be scene support in the future.

**Reply by kingsleyadam** [reply]
Don't forget to authenticate at the top of the page first.
<img width="245" alt="Screenshot 2025-05-29 at 15 04 46" src="https://github.com/user-attachments/assets/7589cd85-9c22-4e17-9e86-9727991747f5" />

**Comment by mattberlinHA** [comment]
I did, but the funny thing is that I get the same dialog no matter whether I am using real credentials or fake credentials.

![image](https://github.com/user-attachments/assets/5391b3be-e580-4dcb-83c0-03a3c431c067)

**Reply by kingsleyadam** [reply]
Just to verify, you're username is likely `installer`, not `install`.

**Reply by mattberlinHA** [reply]
Indeed, I only got the following user accounts and no installer:
<img width="478" alt="image" src="https://github.com/user-attachments/assets/b66d4ce7-7e4f-4971-88c2-e7fb4e7c211e" />

Both, config and Install, have all rights:
<img width="448" alt="image" src="https://github.com/user-attachments/assets/c4615a99-7489-401b-9c1e-be34ba1e9af2" />

**Reply by kingsleyadam** [reply]
The api will use it's own username and ignore your pre-defined usernames. Under the local api credential's it'll show you the username to use, probably `installer`.

<img width="596" alt="Screenshot 2025-05-30 at 10 47 10" src="https://github.com/user-attachments/assets/eb0f8457-1448-4b8c-97c9-1446efae79bd" />

**Reply by mattberlinHA** [reply]
Thank you!

Does this Virtual switch now stay forever?

**Reply by kingsleyadam** [reply]
> Thank you!
> 
> Does this Virtual switch now stay forever?

@derjoerg would probably know best as they have more experience than me. But my understanding is it depends on the `ttl` value. A value of 180 means it'll be there for 3 minutes (180 seconds). A value of `-1` would keep it forever.

**Reply by kingsleyadam** [reply]
The abb documentation has a pretty good write up. https://developer.eu.mybuildings.abb.com/fah_cloud/samples/#how-to-register-a-virtual-device

> Registering for the first time with a friendly name and a TTL value of 3 minutes. This means the virtual device with the Native ID of abcdefgh0123456789 will use the serial 60007F6A06A7. Instead of processing the result of this API endpoint you will find the serial in the output of the configuration endpoint and you get notified about the new virtual device via [websockets](https://developer.eu.mybuildings.abb.com/fah_cloud/concepts#websocket-events) or [webhooks](https://developer.eu.mybuildings.abb.com/fah_cloud/concepts#dJHW2). Later it is enough to send a new lifesign with only a TTL value

> To mark a virtual device as unresponsive (or ready for removal), reregister the device with a TTL value of zero.

> To avoid re-registering the virtual device at regular intervals, the API user can specify a TTL value of -1.

**Reply by mattberlinHA** [reply]
Alright, it's getting better better. I managed to create a virtual device and it also shows up in Home Assistant.
![image](https://github.com/user-attachments/assets/e5bcea04-071f-4727-967b-225d0a190aaa)
The funny thing is, that when turned on it'll turn off right away.

**Reply by derjoerg** [reply]
> The funny thing is, that when turned on it'll turn off right away.

Hey @mattberlinHA 
Have you read through the Wiki regarding Virtual devices and created the necessary automations? https://github.com/kingsleyadam/local-abbfreeathome-hass/wiki/Virtual-Devices

So here some notes:
- Regarding the TTL. I set the ttl to 3600 (seconds) and have an automation, which set this keepalive every 30 minutes. This means, if my HA-instance would be off for over one hour, the virtual devices in F@H would be marked as unresponsive. But as soon as HA is up again, they would return to "live". The automation looks like the following
```
alias: F@H Keepalive
description: ""
triggers:
  - trigger: time_pattern
    minutes: /30
conditions: []
actions:
  - action: abbfreeathome.virtual_device
    data:
      serial: virtual-switch-night
      type: SwitchingActuator
      ttl: 3600
    response_variable: return_var
mode: single
```
- An automation for a virtual switch looks like the following:
```
alias: 21 Nachtmodus
description: ""
triggers:
  - entity_id:
      - switch.nachtmodus
    to: "on"
    id: night_on
    trigger: state
  - entity_id:
      - switch.nachtmodus
    to: "off"
    id: night_off
    trigger: state
  - trigger: event
    event_type: state_changed
    event_data:
      entity_id: event.nachtmodus
    id: night_event
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: night_on
        sequence:
          - data: {}
            target:
              entity_id: input_boolean.verbraucher
            action: input_boolean.turn_off
      - conditions:
          - condition: trigger
            id: night_off
        sequence:
          - data: {}
            target:
              entity_id: input_boolean.verbraucher
            action: input_boolean.turn_on
      - conditions:
          - condition: trigger
            id:
              - night_event
        sequence:
          - variables:
              value: "{{ trigger.event.data.new_state.attributes.event_type == \"On\" }}"
          - choose:
              - conditions:
                  - condition: and
                    conditions:
                      - condition: template
                        value_template: "{{ value }}"
                      - condition: state
                        entity_id: switch.nachtmodus
                        state: "off"
                sequence:
                  - action: switch.turn_on
                    target:
                      entity_id: switch.nachtmodus
                    data: {}
              - conditions:
                  - condition: and
                    conditions:
                      - condition: template
                        value_template: "{{ value == false }}"
                      - condition: state
                        entity_id: switch.nachtmodus
                        state: "on"
                sequence:
                  - action: switch.turn_off
                    target:
                      entity_id: switch.nachtmodus
                    data: {}
mode: queued
max: 10
```

**Comment by Macstar1601** [comment]
@derjoerg I have created an automation which updates my virtual binary window sensors in free@home. Do you have an idea why the window sensors are reseted to off after around 3 min?

**Reply by derjoerg** [reply]
This sounds like the standard ttl.

Which ttl have you set during the creation of the virtual device?

**Reply by Macstar1601** [reply]
I actually created the sensors with ttl=-1. That looked like a good indication. I created a new virtual window contact with ttl=-1 as a test and unfortunately the same thing happens, after 2-3 minutes the sensor turns off.

{
 "type": "BinarySensor",
 "properties": {
 "ttl": "-1",
 "displayname": "Window contact test"
 }
}

**Reply by derjoerg** [reply]
Wow, ok. You are absolutely right. I can confirm this behavior. Shame on me I never looked longer on these states 😢 
I need to have a deeper look on the websocket communication and will reply on any new findings

**Reply by derjoerg** [reply]
Ok, I got a solution, but first:
I played around with the ttl and the keepalive without any success.

Finally, the following automation solved the problem. It checks every two minutes, if the virtual binary sensor is on and if so, switch it on again. This sounds strange, but - well - the F@H API is strange at a lot of places and this is an additional one
```
alias: F@H Workaround
description: ""
triggers:
  - trigger: time_pattern
    minutes: /2
conditions:
  - condition: state
    entity_id: switch.kellerabgangstur
    state: "on"
actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.kellerabgangstur
mode: single
```

@kingsleyadam 
Do you think it is meaningful and/or even possible to add an automatic timer to the integration, which does this check automatically every 2 minutes?

**Reply by kingsleyadam** [reply]
I'm not so sure we want to have thing "ping" type logic in the integration. Seems strange F@H doesn't just keep the state?

Just to confirm, the state is moving to "false" correct? It's not going into an unresponsive state?

**Reply by derjoerg** [reply]
Exactly,
I watched the websocket messages and between 150 and 180 seconds (no static value!) suddenly the state "false" is reported. But only if it was previously "true". So if it is "false" it stays "false" and the websocket is silent.

**Reply by kingsleyadam** [reply]
This almost sounds like an occupancy sensor, is this configurable at all?

**Reply by derjoerg** [reply]
No,
You create a virtual "BinarySensor" and in F@H you specify it as a "window contact". Then you can only state if it is a "opening" or "closing" contact.

I just did a test to rule out this integration to be responsible:
- Opened a dedicated program to listen to websocket messages for the virtual sensor
- Activated the sensor in HA
  - websocket message received
  - sensor turns on in F@H
- Shutdown the switchport of my HA-server
- After the above stated time a websocket message was received, which put the sensor to off

So it is not the integration, which emits the websocket-message, it has to come from F@H

**Comment by Macstar1601** [comment]
Almost the same solution as me :-) What I have noticed is that if you lower the timer too much, it slows down other switching operations in the free@home system via the local API.

This is my solution which checks every 2 minutes and also if the status of a sensor has changed. 


```
alias: Fenster Update Virtuelle Geräte free@home
description: ""
triggers:
  - trigger: time_pattern
    enabled: true
    id: Timer
    minutes: /2
    alias: Timer
  - trigger: state
    entity_id:
      - binary_sensor.fenster_schlafzimmer_contact
    id: schlafzimmer
    alias: schlafzimmer
conditions: []
actions:
  - alias: schlafzimmer
    if:
      - condition: trigger
        id:
          - Timer
          - schlafzimmer
    then:
      - if:
          - condition: state
            entity_id: binary_sensor.fenster_schlafzimmer_contact
            state: "on"
        then:
          - action: switch.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: switch.fensterkontakt_schlafzimmer_abb
      - if:
          - condition: state
            entity_id: binary_sensor.fenster_schlafzimmer_contact
            state: "off"
        then:
          - action: switch.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: switch.fensterkontakt_schlafzimmer_abb
        enabled: true

mode: single
```
