### DISCUSSION TITLE
Is there a way to integrate Busch Welcome?

### DISCUSSION THREAD

**Discussion by domi8671** [kingsleyadam/local-abbfreeathome-hass#150] [General]
I use Free@Home with Busch Welcome. I have a Busch Welcome doorbell and two Free@Home panels as an intercom. Is there any way to integrate this? So that, for example, the doorbell can be integrated into Home Assistant and trigger automations?
Thanks in advance, Dominic

**Comment by alexllax** [comment]
If you do have free@home panels (I guess the old 7" version or maybe the new 10", it doesn't matter), at least in my case, this integration recognizes every panel item (door call, door unlock, etc). You can use these objects to create automations.

**Comment by domi8671** [comment]
Thanks for the quick reply. I use the Busch-SmartTouch 10"
I haven't seen these events before, but after a bit of fiddling around, I figured out that I have to assign them to a room in the f@h config for them to be displayed in HA. So far, so good. However, the doorbell signal sensor isn't displayed. Are the panel's sensors displayed for you?

**Reply by alexllax** [reply]
I haven't assigned any event to a room. This integration just recognizes everything as you can see at the attachement:
![Captura de pantalla 2025-05-31 021134](https://github.com/user-attachments/assets/0f21bfb4-c022-423e-9cb9-45c6cbbfd3e8)

**Reply by derjoerg** [reply]
> Thanks for the quick reply. I use the Busch-SmartTouch 10" I haven't seen these events before, but after a bit of fiddling around, I figured out that I have to assign them to a room in the f@h config for them to be displayed in HA. So far, so good. However, the doorbell signal sensor isn't displayed. Are the panel's sensors displayed for you?

Hi @domi8671 
The doorbell isn't a sensor, it is an event as also shown by @alexllax . Here it how it looks in my installation
![image](https://github.com/user-attachments/assets/54367383-7177-4ed5-9921-be3eb7707461)

A possible automation would looks like this:
```
alias: 10 freeathome Sensors
triggers:
  - trigger: event
    event_type: state_changed
    event_data:
      entity_id: event.smarttouch_10_door_call
    id: door
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: door
        sequence:
          - condition: template
            value_template: >-
              {{ trigger.event.data.new_state.attributes.event_type ==
              "activated" }}
          - target:
              entity_id:
                - script.send_signal_group
            data:
              variables:
                message: Es ist jemand an der Tür!
            action: script.turn_on
            enabled: true
          - data:
              announce: true
              media_content_id: media-source://tts/cloud?message=Es ist jemand an der Tür
              media_content_type: music
              extra:
                volume: 50
            target:
              entity_id:
                - media_player.badbox
                - media_player.dachbox
                - media_player.kellerraum
                - media_player.mobilbox_schwarz
                - media_player.kuchenbox
                - media_player.terrassenbox
                - media_player.wohnzimmerbox
            action: media_player.play_media
            enabled: true
          - data:
              announce: true
              media_content_id: media-source://tts/cloud?message=Es ist jemand an der Tür
              media_content_type: music
              extra:
                volume: 30
            target:
              entity_id:
                - media_player.officebox
                - media_player.nahzimmerbox
            action: media_player.play_media
            enabled: true
mode: queued
max: 10
```
