### DISCUSSION TITLE
Busch Welcome doorbell event is triggered when the integration is reloaded

### DISCUSSION THREAD

**Discussion by domi8671** [kingsleyadam/local-abbfreeathome-hass#165] [General]
The conversation started here:
#150 

I have set up the doorbell event and trigger a notification via an automation.

```yaml
alias: Haustürklingel
description: ""
triggers:
  - trigger: event
    event_type: state_changed
    event_data:
      entity_id: event.panel_dg_door_call
    id: door
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: door
        sequence:
          - condition: template
            value_template: >-
              {{ trigger.event.data.new_state.attributes.event_type ==
              "activated" }}
          - metadata: {}
            data:
              message: Es klingelt an der Haustür.
            action: notify.notificationgroup_domi
          - if:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: person.dominic
                    state: home
                    enabled: true
                  - condition: state
                    entity_id: person.xxx
                    state: home
                    enabled: true
            then:
              - data:
                  message: Es klingelt an der Haustür.
                action: notify.alexa_media_echo_show_5_wohnzimmer
mode: queued
max: 10
```

But when I reload the integration, the event for the doorbell is triggered, and I get a notification that it's ringing.
Is there any way to prevent this?

**Comment by derjoerg** [comment]
I have exactly the same behaviour. It only happens when reloading the integration, when HA is restarted the event isn't fired.

Till now I haven't found anything, which might explain this :cry:

**Comment by kingsleyadam** [comment]
> - trigger: event
>     event_type: state_changed
>     event_data:
>       entity_id: event.panel_dg_door_call
>     id: door

Is it possible to add additional conditions to the event_data? I assume the state is being updated when starting up the integration, I'd be curious to know what that state is.

**Comment by derjoerg** [comment]
So, finally I was able to dig a bit around in this subject.

A "normal" event looks like that:
```
this:
  entity_id: automation.10_freeathome_sensors
  state: 'on'
  attributes:
    id: freeathome_sensors
    last_triggered: '2025-06-21T11:20:19.385934+00:00'
    mode: queued
    current: 0
    max: 10
    friendly_name: 10 freeathome Sensors
  last_changed: '2025-06-17T20:56:25.104963+00:00'
  last_reported: '2025-06-21T11:20:27.626642+00:00'
  last_updated: '2025-06-21T11:20:27.626642+00:00'
  context:
    id: 01JY93FTQAT7R4VHWQRFY6C5TA
    parent_id: null
    user_id: null
trigger:
  id: door
  idx: '2'
  alias: null
  platform: event
  event:
    event_type: state_changed
    data:
      entity_id: event.smarttouch_10_door_call
      old_state:
        entity_id: event.smarttouch_10_door_call
        state: '2025-06-21T11:20:19.359+00:00'
        attributes:
          event_types:
            - activated
          event_type: activated
          device_class: button
          friendly_name: SmartTouch 10 Door call
        last_changed: '2025-06-21T11:20:19.359537+00:00'
        last_reported: '2025-06-21T11:20:30.634592+00:00'
        last_updated: '2025-06-21T11:20:19.359537+00:00'
        context:
          id: 01JY93FJMZ7NDWKEFZMRDE7T54
          parent_id: null
          user_id: null
      new_state:
        entity_id: event.smarttouch_10_door_call
        state: '2025-06-21T13:36:16.095+00:00'
        attributes:
          event_types:
            - activated
          event_type: activated
          device_class: button
          friendly_name: SmartTouch 10 Door call
        last_changed: '2025-06-21T13:36:16.095390+00:00'
        last_reported: '2025-06-21T13:36:16.672381+00:00'
        last_updated: '2025-06-21T13:36:16.095390+00:00'
        context:
          id: 01JY9B8G6ZF5VHXW8M5TWRYW35
          parent_id: null
          user_id: null
    origin: LOCAL
    time_fired: '2025-06-21T13:36:16.095390+00:00'
    context:
      id: 01JY9B8G6ZF5VHXW8M5TWRYW35
      parent_id: null
      user_id: null
  description: event 'state_changed'
```

On a reload of the integration the following "event" is emitted:
```
this:
  entity_id: automation.10_freeathome_sensors
  state: 'on'
  attributes:
    id: freeathome_sensors
    last_triggered: '2025-06-21T14:24:58.317856+00:00'
    mode: queued
    current: 0
    max: 10
    friendly_name: 10 freeathome Sensors
  last_changed: '2025-06-17T20:56:25.104963+00:00'
  last_reported: '2025-06-21T14:24:58.319131+00:00'
  last_updated: '2025-06-21T14:24:58.319131+00:00'
  context:
    id: 01JY9E1NYD9W0HHX5MEARBVCQ5
    parent_id: 01JY9E1NWFYC21NHGMH39CZSM4
    user_id: null
trigger:
  id: door
  idx: '2'
  alias: null
  platform: event
  event:
    event_type: state_changed
    data:
      entity_id: event.smarttouch_10_door_call
      old_state:
        entity_id: event.smarttouch_10_door_call
        state: unavailable
        attributes:
          restored: true
          event_types:
            - activated
          device_class: button
          friendly_name: Door call
          supported_features: 0
        last_changed: '2025-06-21T14:24:58.255383+00:00'
        last_reported: '2025-06-21T14:24:58.255383+00:00'
        last_updated: '2025-06-21T14:24:58.255383+00:00'
        context:
          id: 01JY9E1NWFYC21NHGMH39CZSM4
          parent_id: null
          user_id: null
      new_state:
        entity_id: event.smarttouch_10_door_call
        state: '2025-06-21T13:36:16.095+00:00'
        attributes:
          event_types:
            - activated
          event_type: activated
          device_class: button
          friendly_name: SmartTouch 10 Door call
        last_changed: '2025-06-21T14:24:59.279387+00:00'
        last_reported: '2025-06-21T14:24:59.279387+00:00'
        last_updated: '2025-06-21T14:24:59.279387+00:00'
        context:
          id: 01JY9E1PWFHCNME1CK4GRRSNYQ
          parent_id: null
          user_id: null
    origin: LOCAL
    time_fired: '2025-06-21T14:24:59.279387+00:00'
    context:
      id: 01JY9E1PWFHCNME1CK4GRRSNYQ
      parent_id: null
      user_id: null
  description: event 'state_changed'
```

Looking closer to this on a reload of the integration even two events are emitted:
1. An event where the state changes from "last triggered date" to "unavailable" (when the integration is unloaded)
2. An event where the state changes from "unavailable" to "last triggered date" (when the integration is loaded again) and also the attribute "restored: true" is now set

I found an interessting write-up in the following post: https://community.home-assistant.io/t/using-the-new-action-events-in-zigbee2mqtt-2-0/821709

For the door call this means that the following trigger is working as expected:
```
triggers:
  - trigger: state
    entity_id:
      - event.smarttouch_10_door_call
    not_from: unavailable
    not_to: unavailable
    id: door
```

Slim and easy 😉

**Comment by derjoerg** [comment]
I think (but this is really only my personal thought):
In the past this was really the correct way to handle such events (trigger: event), but when HA introduced event-entities this concept needed to be re-thought and now "trigger: state" should be the way forward.

And looking in the above linked post regarding Z2M this should also apply to switches and you do the necessary differentiation with a `choose` condition `trigger.to_state.attributes...`

**Comment by domi8671** [comment]
I changed the trigger to trigger: state and it works as expected. Thanks for the help.

I already use trigger: state for my switches, but without a template. It looks like this:
```yaml
alias: Beleuchtung UG Vorraum (Schalter)
description: ""
triggers:
  - trigger: state
    entity_id: event.schalter_ug_vr
conditions: []
actions:
  - choose:
      - conditions:
          - alias: UG VR Licht off
            condition: state
            entity_id: event.schalter_ug_vr
            attribute: event_type
            state: "off"
        sequence:
          - action: input_boolean.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: input_boolean.beleuchtung_ug_vorraum
      - conditions:
          - alias: UG VR Licht on
            condition: state
            entity_id: event.schalter_ug_vr
            attribute: event_type
            state: "on"
        sequence:
          - action: input_boolean.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: input_boolean.beleuchtung_ug_vorraum
mode: queued
max: 10
```
