### ISSUE TITLE
Busch Welcome doorbell event is triggered when the integration is reloaded

### ISSUE THREAD

**Issue by domi8671** [kingsleyadam/local-abbfreeathome-hass#162]
The conversation started here:
#150 

I have set up the doorbell event and trigger a notification via an automation.

```yaml
alias: Haustürklingel
description: ""
triggers:
  - trigger: event
    event_type: state_changed
    event_data:
      entity_id: event.panel_dg_door_call
    id: door
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: door
        sequence:
          - condition: template
            value_template: >-
              {{ trigger.event.data.new_state.attributes.event_type ==
              "activated" }}
          - metadata: {}
            data:
              message: Es klingelt an der Haustür.
            action: notify.notificationgroup_domi
          - if:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: person.dominic
                    state: home
                    enabled: true
                  - condition: state
                    entity_id: person.xxx
                    state: home
                    enabled: true
            then:
              - data:
                  message: Es klingelt an der Haustür.
                action: notify.alexa_media_echo_show_5_wohnzimmer
mode: queued
max: 10
```

But when I reload the integration, the event for the doorbell is triggered, and I get a notification that it's ringing.
Is there any way to prevent this?
